build:
	@echo Building...
	@go mod tidy
	go build ./cmd/main.go
format:
	@gofumpt -w .
	@wsl -fix ./...
lint:
	@echo Linting...
	@golangci-lint run
test:
	@echo Running tests ...
	@go test -race -coverprofile test/out/cover.out ./...
	@go tool cover -html=test/out/cover.out
.PHONY: build lint format test