// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package grmodels

import (
	"time"
)

type Comment struct {
	ID        string     `json:"id"`
	Author    *User      `json:"author"`
	Published time.Time  `json:"published"`
	Text      string     `json:"text"`
	PostID    string     `json:"postID"`
	Replies   []*Comment `json:"replies,omitempty"`
}

type CommentInput struct {
	Author        *UserInput `json:"author"`
	Text          string     `json:"text"`
	PostID        string     `json:"postID"`
	ParentComment string     `json:"parentComment"`
}

type Mutation struct {
}

type Post struct {
	ID              string     `json:"id"`
	Author          *User      `json:"author"`
	Text            string     `json:"text"`
	Published       time.Time  `json:"published"`
	DisableComments bool       `json:"disableComments"`
	Comments        []*Comment `json:"comments,omitempty"`
}

type PostInput struct {
	AuthorID        string `json:"authorID"`
	Text            string `json:"text"`
	DisableComments bool   `json:"disableComments"`
}

type Query struct {
}

type User struct {
	ID string `json:"id"`
}

type UserInput struct {
	ID string `json:"id"`
}
